name: test-g
on:
  push:
    branches: [test/g]
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git remote add forge https://github.com/Card-Forge/forge.git
          git remote -v
      - run: gh pr create --base master --head test/g --title "test g" --body "debug"
